CREATE TABLE CLIENTE (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTO (
    ID SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    PRECO_UNITARIO NUMERIC(20,2)
);

CREATE TABLE PEDIDO (
    ID SERIAL PRIMARY KEY,
    CLIENTE_ID INTEGER REFERENCES CLIENTE(ID),
    DATA_PEDIDO TIMESTAMP,
    VALOR_TOTAL NUMERIC(20,2)
);

CREATE TABLE ITEM_PEDIDO (
    ID SERIAL PRIMARY KEY,
    PEDIDO_ID INTEGER REFERENCES PEDIDO(ID),
    PRODUTO_ID INTEGER REFERENCES PRODUTO(ID),
    CLIENTE_ID INTEGER REFERENCES CLIENTE(ID),
    QUANTIDADE INTEGER
);